version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                key: yarn-{{checksum "yarn.lock"}}
            - run:
                name: Install dependencies
                command:
                    yarn
            - save_cache:
                key: yarn-{{checksum "yarn.lock"}}
                paths: ~/.cache/yarn
            - run:
                name: Run test
                command:
                    yarn test
            - store_test_results:
                path: ./test-results.xml
            - store_artifacts:
                path: ./test-results.xml